<a href="https://colab.research.google.com/github/joepetrucci11/Data-Sci/blob/main/Petrucci_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [81]:
import numpy as np # numpy is a set of tools

In [82]:
for i in range(100): # this is called a for loop and this one will output a varibale 100 times
   print(i) # this prints out the variable 'i' each time it loops until the max amount for the loop

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [83]:
for i in range(10): # this is called a for loop and this one will output a varibale 10 times
  print('₉⁹₉') # this prints out the variable '₉⁹₉' each time it loops until the max amount for the loop

₉⁹₉
₉⁹₉
₉⁹₉
₉⁹₉
₉⁹₉
₉⁹₉
₉⁹₉
₉⁹₉
₉⁹₉
₉⁹₉


In [84]:
for i in range(5,8): # this is a for loop with a range between 5 and 8. Therefore it will output 3 numbers
    print(i) # this prints out the variable 'i' each time it loops until the max amount for the loop. The last number in the range is not inclusive

5
6
7


In [85]:
for i in range(3): # this is a for loop that will output 3 numbers
    print( "Test Number: " , i ) # this prints out the words "Test Number" followed by the variable 'i' which holds the values from 0 to 2 ( which is 3 numbers ) because python starts counting from 0 instead of 1

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [86]:
def square(x): # here we are defining a square function for a number that is stored in variable 'x'
    return x**2 # this is the operation that will be carried out in order to square a number stored in variable 'x'

In [87]:
square(5) # here we are using the function to square the number 5 stored in variable 'x' and output the results

25

In [88]:
square(square(2)) # here we have a compound/ composite function where firstly we are squaring the number 2 stored in variable 'x' and then secondly squaring the result of that 

16

In [89]:
square(square(square(2))) # here we have a compound/ composite function where firstly we are squaring the number 2 stored in variable 'x' then secondly squaring the result of that and finally sqauring the result of that


256

In [90]:
square(123456) # here we are using the function to square the number 123456 stored in variable 'x' and output the results

15241383936

In [91]:
square(square(5)) # here we have a compound/ composite function where firstly we are squaring the number 5 stored in variable 'x' and then secondly squaring the result of that 

625

In [92]:
def add_two(x): # here we are defining a function that adds 2 to a number stored in variable 'x'
    return x+2 # this is the operation that will be carried out in order to add 2 to a number stored in variable 'x'

In [93]:
add_two(5) # here we are using the function to add 2 to the number 5 stored in variable 'x' and output the results

7

In [94]:
square(add_two(5)) # here we have a compound/ composite function where we are adding 2 to the number 5 stored in variable 'x' then squaring the result and outputing it 

49

### Logical Branching

In [95]:
choice = "apple" # we are storing the word "apple" in the variable 'choice'

In [96]:
if choice == "apple": # this is a nested if then else statement. Double equal means that it will check if both things on either side are equal and will give me a true

    print("You choose apples.") # this will output "You choose apples." if true 

else: # Otherwise
    
    print("You did not choose apples.") # this will output "You did not choose apples." 

You choose apples.


In [97]:
choice = "orange" # we are storing the word "orange" in the variable 'choice'

In [98]:
if choice == "apple": # this is a nested if then else statement. Double equal means that it will check if both things on either side are equal and will give me a true

    print("You choose apples.") # this will output "You choose apples." if true 

else: # Otherwise
    
    print("You did not choose apples.") # this will output "You did not choose apples."

You did not choose apples.


In [99]:
choice = "apple" # we are storing the word "apple" in the variable 'choice'

In [100]:
if choice == "apple": # this is a nested if then else statement. Double equal means that it will check if both things on either side are equal and will give me a true

    print("You choose apples.") # this will output "You choose apples." if true 
    print("Thank you, shop again!") # this will output "Thank you, shop again!" if true 
    print(2**123) # this will output the result of 2^123 (2 to the power of 123) if true 

elif choice == "orange": #this is called an else if statement. Double equal means that it will check if both things on either side are equal and will give me a true

    print("You choose oranges.") # this will output "You choose oranges." if true 
    print("Thank you, shop again!") # this will output "Thank you, shop again!" if true 

else: # Otherwise
    
    print("You did not choose apples or oranges.") # this will output "You did not choose apples or oranges." 
    print("Thank you, shop again!") # this will output "Thank you, shop again!"

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [101]:
choice = input("Please enter your choice (i.e. apple): ") # this prompts the user to enter a choice which in this case they entered bananas

Please enter your choice (i.e. apple): 


In [102]:
choice # this outputs what is being held in the variable 'choice'

''

In [103]:
if choice == "apple": # this is a nested if then else statement. Double equal means that it will check if both things on either side are equal and will give me a true

    print("You choose apples.") # this will output "You choose apples." if true 

elif choice == "oranges": #this is called an else if statement. Double equal means that it will check if both things on either side are equal and will give me a true

    print("You choose oranges.") # this will output "You choose oranges." if true 

else: # Otherwise
    
    print("You did not choose apples or oranges.") # this will output "You did not choose apples or oranges." 

You did not choose apples or oranges.


#### Coins

In [104]:
np.random.random() # this is used to generate a random number

0.06622782144896688

In [105]:
np.random.random() > 0.5 # this is used to tell if the number is greater than 0.5 (True) or less than 0.5 (False)

True

In [106]:
def flip_coin(): # we have defined the variable flip_coin and have given it some function to carry out
    if np.random.random() > 0.5: # we are using a nested if then else statement to get either True or False if a number is greater than 0.5
        print("Heads") # if True, it will print out Heads
    else: # Otherwise
        print("Tails") # if False it will print out Tails

In [107]:
flip_coin() # here we are executing the function

Heads


### Graphics Output

In [108]:
from IPython.core.display import display, HTML # tools from a library

In [109]:
display(HTML('<h1>Hello, world!</h1>')) # this is used to display the text "Hello World!" in a Header Format

In [110]:
def coin(): # we have defined the variable coin and have given it some function to carry out
  return np.random.randint(2) # this gives us a random integer either 0 or 1

In [111]:
coin() # here we are executing the function

0

In [112]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))
# here we are displaying an image of the Heads side of a coin from the Internet

In [113]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'# here we are displaying an image of the Heads side of a coin from the Internet
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'# here we are displaying an image of the Tails side of a coin from the Internet

In [114]:
def show_img(img): # here we are defining a function that will display an image
  display(HTML('<img src=' + img + '>')) # this outputs the image 

In [115]:
show_img(heads) # here we are executing the function and displaying the heads outcome

In [116]:
show_img(tails) # here we are executing the function and displaying the tails outcome

In [117]:
def flip_coin(): # here we are defining a function that will display an image depending on the outcome of the nested if then else statement

    if coin():
        show_img(heads) # this will show the image for heads if true
    else:
        show_img(tails) # this will show the image for tails if false

In [118]:
flip_coin() # here we are executing the function 

In [119]:
for i in range(5): # here we are executing the function in a for loop which will give us 5 outputs 
    flip_coin()

In [120]:
#@title Coin_Flip

if coin(): # here we have a function that will display an image depending on the outcome of the nested if then else statement

  show_img(heads) # this will show the image for heads if true

else:

  show_img(tails) # this will show the image for tails if false

### Cards

In [121]:
def shuffle(x): # we have defined the variable shuffle and have given it some function to carry out
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        print(j,x)
    return x

In [122]:
a = np.arange(52) # here we have assigned an array with 52 positions/numbers to the variable 'a'

In [123]:
shuffle(a) # here we are executing the function 

23 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 51
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 23]
10 [ 0  1  2  3  4  5  6  7  8  9 50 11 12 13 14 15 16 17 18 19 20 21 22 51
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 10 23]
21 [ 0  1  2  3  4  5  6  7  8  9 50 11 12 13 14 15 16 17 18 19 20 49 22 51
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 21 10 23]
3 [ 0  1  2 48  4  5  6  7  8  9 50 11 12 13 14 15 16 17 18 19 20 49 22 51
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  3 21 10 23]
17 [ 0  1  2 48  4  5  6  7  8  9 50 11 12 13 14 15 16 47 18 19 20 49 22 51
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 17
  3 21 10 23]
12 [ 0  1  2 48  4  5  6  7  8  9 50 11 46 13 14 15 16 47 18 19 20 49 22 51
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 12 17
  3 21 10 23]
3 [ 0  1  2 45  4  5  6

array([49,  6, 25,  2, 19, 34,  1, 45, 29, 44, 14, 24,  7, 50, 40, 41, 27,
       33,  5, 36, 42, 20, 16, 28, 43, 31,  9, 11, 38, 22, 35,  0, 47, 30,
       15, 37, 39, 26, 32, 13, 18, 46,  4, 51,  8, 48, 12, 17,  3, 21, 10,
       23])

In [124]:
np.random.permutation(52) # This is just a simpler and easier way of executing the function 

array([30, 33, 42, 41, 40, 35, 19, 47, 15, 43, 25, 37, 18, 39, 23, 50,  7,
       49, 28, 27, 31,  5, 36,  9, 51,  4, 48, 21, 22, 24,  3,  0, 17, 32,
       11, 29, 44, 34,  2, 16, 46, 45,  8, 14, 38, 20, 26,  1, 13, 12,  6,
       10])

### Speed Test

In [125]:
%%timeit
shuffle(a) # this is an easy way of getting the times for the execution of this function

Streaming output truncated to the last 5000 lines.
 12 46 39 44]
12 [48 11 35 27 20  7 31 10 15  1 17  2 49 19  0 42 36 41 28  8  4 13 43 22
 30 29 45 40 21 23 37 18 24 38 25 51 50 32 34  9  6 47  3 14 33  5 26 16
 12 46 39 44]
22 [48 11 35 27 20  7 31 10 15  1 17  2 49 19  0 42 36 41 28  8  4 13 38 22
 30 29 45 40 21 23 37 18 24 43 25 51 50 32 34  9  6 47  3 14 33  5 26 16
 12 46 39 44]
1 [48 24 35 27 20  7 31 10 15  1 17  2 49 19  0 42 36 41 28  8  4 13 38 22
 30 29 45 40 21 23 37 18 11 43 25 51 50 32 34  9  6 47  3 14 33  5 26 16
 12 46 39 44]
20 [48 24 35 27 20  7 31 10 15  1 17  2 49 19  0 42 36 41 28  8 18 13 38 22
 30 29 45 40 21 23 37  4 11 43 25 51 50 32 34  9  6 47  3 14 33  5 26 16
 12 46 39 44]
6 [48 24 35 27 20  7 37 10 15  1 17  2 49 19  0 42 36 41 28  8 18 13 38 22
 30 29 45 40 21 23 31  4 11 43 25 51 50 32 34  9  6 47  3 14 33  5 26 16
 12 46 39 44]
1 [48 23 35 27 20  7 37 10 15  1 17  2 49 19  0 42 36 41 28  8 18 13 38 22
 30 29 45 40 21 24 31  4 11 43 25 51 50 32 34  

In [126]:
%%timeit
np.random.permutation(52) # this is an easy way of getting the times for the execution of this function

3.75 µs ± 315 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [127]:
np.random.permutation(52) # This is just a simpler and easier way of executing the function 

array([26, 45, 49, 40, 35, 38, 21,  6, 27, 42,  7, 51, 28,  5, 18, 36,  2,
       46, 44, 19, 50, 30, 14, 33, 47,  0, 22, 16, 41, 23,  1, 37, 13, 43,
        9,  8, 31, 29, 39, 10, 25, 20, 15,  4, 17,  3, 24, 11, 48, 32, 34,
       12])

In [128]:
cards = np.random.permutation(52) # here we are assigning the values of the array to the variable 'cards'

In [129]:
cards # here we are displaying what the variable 'cards' holds

array([44, 48, 29, 40, 13, 42, 25, 21, 37, 35, 46, 24, 33, 10,  4, 26, 49,
       41, 19, 23,  8, 20,  0, 18, 27, 11, 47, 32,  3, 16, 51, 28, 38, 17,
        2, 22,  1, 50, 15, 34, 30, 43, 45, 12,  6, 39,  7, 36,  9, 14,  5,
       31])

In [130]:
cards[0] # here we are asking for the number in the first position of the array

44

In [131]:
cards[1] # here we are asking for the number in the second position of the array

48

In [132]:
cards[2] # here we are asking for the number in the third position of the array

29

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>
    
    # this is an image of a deck of cards from the Internet

In [133]:
np.arange(52).reshape(4,13) # here we are asking for an array of 52 numbers which will be reshaped into 4 rows and 13 columns 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [134]:
np.arange(52).reshape(4,13)%13 # this is another way of achieving the same arrangement of 4 rows and 13 columns but with different numbering this time

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [135]:
np.arange(52).reshape(4,13)//13 # this is another way of achieving the same arrangement of 4 rows and 13 columns but with different numbering this time

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [136]:
suits = ['Clubs','Spades','Hearts','Diamonds'] # this is an array of suits of cards
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] # this is an array of different cards in a suit

In [137]:
def card_name(card_number): # we have defined the variable card_name and have given it some function to carry out
    
    suit = card_number//13 # we have assigned this arrangement to the variable 'suit'
    name = card_number%13 # we have assigned this arrangement to the variable 'name'

    return names[name] + " of " + suits[suit] # here we are formating the output to say "___(card) of ___(suit)"

In [138]:
card_name(0) # here we are executing the function and diplaying the first position of the array using the formating

'Ace of Clubs'

In [139]:
card_name(51) # here we are executing the function and diplaying the last position of the array using the formating

'King of Diamonds'

In [140]:
cards = np.random.permutation(52) # here we are assigning the values of the array to the variable 'cards'

In [141]:
top_of_deck         = card_name(cards[0]) # here we are assigning the first position of the array using the formating to the 'variable top_of_deck'
second_card_in_deck = card_name(cards[1]) # here we are assigning the second position of the array using the formating to the 'second_card_in_deck'
last_card_in_deck   = card_name(cards[-1]) # here we are assigning the last position of the array using the formating to the 'last_card_in_deck'

In [142]:
top_of_deck, second_card_in_deck, last_card_in_deck # here we are displaying what each variable holds

('Five of Hearts', 'Ace of Spades', 'Ten of Hearts')

In [143]:
for i in range(5): # this is called a for loop and this one will output a variable 5 times
    print(card_name(cards[i])) # this will output the first five positions of the array using the formating 

Five of Hearts
Ace of Spades
Two of Spades
Six of Diamonds
Eight of Diamonds


In [144]:
for i in range(15): # this is called a for loop and this one will output a variable 15 times
    print(card_name(cards[i])) # this will output the first fifteen positions of the array using the formating 

Five of Hearts
Ace of Spades
Two of Spades
Six of Diamonds
Eight of Diamonds
Four of Clubs
Five of Spades
Nine of Diamonds
Six of Spades
Queen of Diamonds
Four of Hearts
Ace of Hearts
Nine of Clubs
Two of Hearts
Seven of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

    #this is a guide to help with the cards in a deck/pack

In [145]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" # here we are displaying an image of the Heads side of a card from the Internet
card_url_tail = ".png" # here we are displaying an image of the Tails side of a card from the Internet

In [146]:
suit = ['k','p','s','l'] # this is an array of suits of cards by the first letter of their suit
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k'] # this is an array of different cards in a suit in order

In [147]:
i = np.random.randint(4) # this gives a random integer between 0 and 3 then stores it in variable 'i' 
j = np.random.randint(13) # this gives a random integer between 0 and 12 then stores it in variable 'j' 

In [148]:
i,j # here we are displaying the positions in the array stored in the variables 'i' and 'j'

(2, 7)

In [149]:
suit[i] # here we are displaying the corresponding suit based on the position in the array

's'

In [150]:
card[j] # here we are displaying the corresponding card based on the position in the array

'8'

In [151]:
from IPython.core.display import display, HTML # tools from a library

In [152]:
def show_img(img): # here we are defining a function that will display an image
  display(HTML('<img src=' + img + '>')) # this outputs the image 

In [153]:
img = card_url_head + suit[i] + card[j] + card_url_tail # here we have assigned the heads image, suit, card and tails image to the variable 'img'

In [154]:
show_img(img) # here we are executing the function

In [155]:
def card_image(card_number): # we have defined the variable card_image and have given it some function to carry out
    
    i = card_number//13 # we have assigned this arrangement to the variable 'i'
    j = card_number%13 # we have assigned this arrangement to the variable 'j'

    return suit[i]+card[j] # here we are formating the output to say "___(first letter of suit) ___(card)"

In [156]:
card_image(3) # here we are executing the function

'k4'

In [157]:
img = card_url_head + card_image(3) + card_url_tail # here we are assigning the head image of the card, the corresponding card and the tails image of the card to the variable 'img'

In [158]:
show_img(img) # here we are executing the function

In [160]:
for i in range(52): # this is called a for loop and this one will output the image associated with each position of the array a total of 52 times
    img = card_url_head + card_image(i) + card_url_tail 
    show_img(img)